# Generated by Django 2.2.10 on 2020-03-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parkings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lmpPID', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('provider', models.CharField(max_length=60)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
