# Generated by Django 2.2.10 on 2020-03-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parkings',
            table='parkings',
        ),
    ]
